### PR TITLE
Support AVA 4

### PR DESCRIPTION
**Pull request by bitjson**
Closes https://github.com/dubzzz/ava-fast-check/issues/62

I'm not entirely sure what's going on with the tests yet, but this appears to fix the type issues enough for my projects to work.

### CODE REVIEW

**Comment by dubzzz** [comment]
Whaou thank you so much 👍

I was planning to handle the bump but I have not find any time to do that recently.  I believe that ava 4 does not support node 10 and 12. We should probably drop support for them in fast-check too so that the test will pass (+ add node 16 instead?).

**Comment by bitjson** [comment]
Thanks for the quick response! Looking forward to pulling this into my projects. (AVA 4 makes pure ESM very simple, so getting `ava-fast-check` upgraded removes the last barrier there for me.)

Dropping 10 and 12 and adding node 16 makes sense to me 👍

**Comment by dubzzz** [comment]
I'm updating the GH actions defines on the repository to stop testing against node 12, 14

**Comment by dubzzz** [comment]
@bitjson I let you retry after having refresh your branch with current main. As I bumped towards more recent versions of node it should be ok now.

**Comment by dubzzz** [comment]
@bitjson main branch as been updated (see previous message), if merge it back in your PR, I hope tests will make it this time 🤞

**Comment by bitjson** [comment]
@dubzzz sorry for the delay, I haven't had much time to continue on this – thanks for bumping the versions!

This patch has been working in my project, but I haven't quite figured out the import issue which is causing the tests to fail. If you have a good sense of what's going on, I'd appreciate you taking a look!

**Comment by dubzzz** [comment]
Thanks for the merge of main branch. I'll double check what can fail in the PR in the coming days

**Comment by dubzzz** [comment]
@bitjson Let's give a try to a fix 🤞 See name of the commit for more details on the why such fix

**Comment by bitjson** [comment]
Ah fantastic! Looks like everything is working now, thanks! 🚀

**Comment by dubzzz** [comment]
Version 5.0. has been published to npm with support for ava 4.0.0 and above, thanks for the bump

**Pull request merged**
