### PR TITLE
Add support for test.serial

### PR DESCRIPTION
**Pull request by CodeLenny**
I've added support for Ava's `test.serial()` as it would be useful for my tests.

### CODE REVIEW

**Comment by dubzzz** [comment]
Commits merged, thanks a lot for the contribution. I will publish a new version of ava-fast-check soon

**Comment by CodeLenny** [comment]
@dubzzz Thanks!

**Comment by dubzzz** [comment]
Version 1.1.0 on its way (travis should publish it soon)

**Comment by CodeLenny** [comment]
@dubzzz I think Travis failed to publish to NPM due to a missing Git tag.  Might you be able to take a look?  Thanks!

**Pull request merged**
