### PR TITLE
fix: bump fast-check peer dependency

### PR DESCRIPTION
**Pull request by bitjson**
Hey @dubzzz, thanks for this library! It's definitely helped to clean up my fast-check tests. 

I noticed you recently released [fast-check v2.0.0](https://github.com/dubzzz/fast-check/releases/tag/v2.0.0), but `ava-fast-check` [still has a peer dependency](https://github.com/dubzzz/ava-fast-check/blob/master/package.json#L29) of
`"fast-check": "^1.0.0"`. 

Does this just need to be updated, or is there a compatibility issue I haven't noticed?

### CODE REVIEW

**Comment by dubzzz** [comment]
Indeed! Actually I was supposed to do it with https://github.com/dubzzz/ava-fast-check/pull/12 but I totally forgot to update it with the latest major of fast-check

**Comment by dubzzz** [comment]
As soon as I merge https://github.com/dubzzz/ava-fast-check/pull/12, ava-fast-check might not be compatible with ^1.0.0.

The PR brings full support for CommonJS and ES Modules in ava-fast-check but if I am not wrong it made it incompatible with 1.0.0. Let's me retry locally when I merge https://github.com/dubzzz/ava-fast-check/pull/12

**Comment by dubzzz** [comment]
@bitjson I went through your PR and adapted it to only target `^2.0.0` for now. Once green (CI), I'll merge it and start a release process.

**Comment by dubzzz** [comment]
@bitjson I just released `ava-fast-check@3.0.0`. If I am not wrong it may not work with `fast-check@^1.0.0`. So for the moment, I only put `fast-check@^2.0.0` as a peer dependency.

If you make it work properly with `^1.0.0` we may update the peer to `^1.0.0 || ^2.0.0`. I prefer being strict on the range.
By the way, in case you need it, I can publish a new `àva-fast-check@1.x.x` or `àva-fast-check@2.x.x` with peer being `^1.0.0 || ^2.0.0`.

**Comment by bitjson** [comment]
Great, thanks!

> **By the way version 2.0.0 of ava-fast-check includes a breaking change, see #11**

Already [updated](https://github.com/bitauth/libauth/commit/21f8f478d4b111a5807384480e9f282698fc9593) last week 😄 – I appreciate the new API! Makes the fast-check tests much more similar in style to other AVA tests. 👍

**Pull request merged**
